plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace 'com.nishanth.simplecomposeui'
    compileSdk 36

    defaultConfig {
        applicationId "com.nishanth.simplecomposeui"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.8"
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {

    // Jetpack Compose BOM (manages Compose versions consistently)
    implementation(platform("androidx.compose:compose-bom:2024.02.00"))

    implementation("com.google.android.material:material:1.11.0")

    // Compose (not directly used in widget, but required for project setup)
    implementation("androidx.activity:activity-compose:1.9.0")
    implementation(platform("androidx.compose:compose-bom:2024.02.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation libs.androidx.animation.core
    implementation libs.androidx.navigation.runtime.ktx
    implementation libs.androidx.material3
    debugImplementation("androidx.compose.ui:ui-tooling")

    implementation  libs.accompanist.navigation.animation
    implementation("androidx.compose.material:material-icons-extended:1.7.0")


}